### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sko00o** [sko00o/sko00o.github.io#2]
> 写一个公开的清单，督促自己学习，多做内容输出。

- [ ] [Playwright](https://playwright.dev/) 微软开发的网页自动化测试框架。
- [ ] [testcontainers-go](https://golang.testcontainers.org/) 使用容器对程序进行自动化/集成测试。
- [ ] Semantic Kernel

ChatGPT prompt engineering:
- [ ] https://github.com/dair-ai/Prompt-Engineering-Guide
- [ ] https://github.com/f/awesome-chatgpt-prompts

Learning Rust:
- [ ] https://google.github.io/comprehensive-rust/
- [ ] https://rust-lang.github.io/async-book/

ML learning:
- https://mlu-explain.github.io/
